---
name: tests
on:
  push:
    branches:
      - main
      - '*.*.*'
  pull_request:
    branches:
      - main
      - '*.*.*'

jobs:
  tests:
    name: ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.12'
          - '3.11'
          - '3.10'
          - '3.9'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'
      - name: Install dependencies and run tests
        run: |
          poetry --version
          poetry install
          poetry run pytest --showlocals
      - name: Run scim2-server tests
        if: ${{ matrix.python != '3.9' && matrix.python != '3.10' }}
        run: |
          cd examples/scim2-server
          poetry install --with test
          poetry run pytest --showlocals

  minversions:
    name: minimum dependency versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: sed -i -E 's/"(\^|>=)([0-9\.]+)([^,]*)"/"==\2"/' pyproject.toml
      - run: sed -i -E 's/python = "==/python = "^/' pyproject.toml
      - name: Install dependencies and run tests
        run: |
          poetry --version
          poetry lock
          poetry install
          poetry run pytest --showlocals

  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: |
          poetry install --with doc
          poetry run sphinx-build doc build/sphinx/html
